POST http://localhost:3000/seller-orders
Content-Type: application/json

{   
      "seller_price": 100,
      "seller_qty": 20
}

###
POST http://localhost:3000/buyer-orders
Content-Type: application/json

{   
      "buyer_price": 100,
      "buyer_qty": 20
}

###
GET http://localhost:3000/seller-pending-orders

###
GET http://localhost:3000/buyer-pending-orders

###

GET http://localhost:3000/completed-orders

###

POST http://localhost:3000/match-orders
Content-Type: application/json

{   
      "buyer_price": 100,
      "buyer_qty": 20
}